services:
  - type: web
    name: beer-counter
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.prod.js
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: beer-data
      mountPath: /data
      sizeGB: 1
    autoDeploy: false 