export const PLAYERS = [
  { value: 'Guille', label: 'Guille', passcode: '14' },
  { value: 'Gianni', label: 'Gianni', passcode: '29' },
  { value: 'Armando', label: 'Armando', passcode: '00' },
  { value: 'Pablo', label: 'Pablo', passcode: '08' },
  { value: 'Titan', label: 'Titan', passcode: '20' },
  { value: 'Nico', label: 'Nico', passcode: '15' },
  { value: 'Kiki', label: 'Kiki', passcode: '10' },
  { value: 'Vitoko', label: 'Vitoko', passcode: '85' },
  { value: 'Unger', label: 'Unger', passcode: '01' },
  { value: 'Hernández', label: 'Hernández', passcode: '07' },
  { value: 'Garreaud', label: 'Garreaud', passcode: '30' },
  { value: 'Landa', label: 'Landa', passcode: '09' },
  { value: 'Igi', label: 'Igi', passcode: '11' },
  { value: 'Gosen', label: 'Gosen', passcode: '33' },
  { value: 'Rivera', label: 'Rivera', passcode: '191' },
  { value: 'Sandoval', label: 'Sandoval', passcode: '69' },
  // Add more players as needed
];

export const BEER_BRANDS = [
  { value: 'estrella_damm', label: 'Estrella Damm' },
  { value: 'heineken', label: 'Heineken' },
  { value: 'san_miguel', label: 'San Miguel' },
  { value: 'corona', label: 'Corona' },
  { value: 'estrella_galicia', label: 'Estrella Galicia' },
  { value: 'cristal', label: 'Cristal' },
  { value: 'coors', label: 'Coors' },
  { value: 'budweiser', label: 'Budweiser' },
  { value: 'austral', label: 'Austral' },
  { value: 'kuntsmann', label: 'Kuntsmann' },
  { value: 'guinness', label: 'Guinness' },
  { value: 'quilmes', label: 'Quilmes' },
  { value: 'becker', label: 'Becker' },
  { value: 'escudo', label: 'Escudo' },
  { value: 'patagonia', label: 'Patagonia' },
  { value: 'sol', label: 'Sol' },
  { value: 'stella_artois', label: 'Stella Artois' },
  { value: 'peroni', label: 'Peroni' },
  { value: 'vitokos_brew', label: 'Vitokos Brew' },
  { value: 'royal', label: 'Royal' },
  { value: 'tamango', label: 'Tamango' },
  { value: 'jester', label: 'Jester' },
  { value: 'mahou', label: 'Mahou' },
  { value: 'dolbek', label: 'Dolbek' },
  { value: 'otras', label: 'Otras' },
  { value: 'kross', label: 'Kross' },
  { value: 'cusqueña', label: 'Cusqueña' },
];

export const VOLUMES = [
  { value: 0.2, label: '0.2L' },
  { value: 0.33, label: '0.33L' },
  { value: 0.5, label: '0.5L' },
  { value: 1, label: '1L' },
  // Add more volumes as needed
]; 